# -*- coding: utf-8 -*-
"""dbmodel.ipynb
Created on Sat Jan 30 15:04:25 2021

@author: uday chowdary adusumilli
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pozcN2Sz1Cb0lV4FbdM5eZab4kAN3Wij
"""
import sqlite3


def sql(sqltext):
    rows = None
    column_names = []
    if len(sqltext) > 0:
        mysql_conn = sqlite3.connect('./transport.db')
        my_cursor = mysql_conn.cursor()
        #print(sqltext)
        my_cursor.execute(sqltext)
        # get the column names
        for c in my_cursor.description:
            column_names.append(c[0])
        # get the data
        rows = my_cursor.fetchall()
        #print(column_names)
        #for drow in rows:
        # print(drow)
    return rows, column_names


# USE THIS BLOCK OF CODE FOR UNIT TESTING OR DEBUGGING
'''
#sqltext = "select * from track where operation_status = 'transit'"
result = sql(sqltext)
col_name = []
for k in result[0]:
  print(k)
  col_name.append(k)
'''